# Generated by Django 4.1.2 on 2023-03-20 07:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('shopapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='HistoryChat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(max_length=50, verbose_name='Staus chat')),
                ('content', models.CharField(blank=True, max_length=1000, verbose_name='Content chat')),
                ('has_image', models.BooleanField(blank=True, default=False, verbose_name='Has image')),
                ('user', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_chat', to='shopapp.userprofile')),
            ],
        ),
    ]
