# Generated by Django 4.1.2 on 2023-03-24 10:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shopapp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='historicalproductcategory',
            name='code',
        ),
        migrations.RemoveField(
            model_name='historicalwallet',
            name='code',
        ),
        migrations.RemoveField(
            model_name='productcategory',
            name='code',
        ),
        migrations.RemoveField(
            model_name='wallet',
            name='code',
        ),
    ]
