# Generated by Django 4.1.2 on 2023-03-02 11:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shopapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserPolicy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.IntegerField(choices=[(0, 'Admin'), (1, 'Staff'), (2, 'Custommer')], verbose_name='Policy Name')),
                ('description', models.CharField(max_length=200, verbose_name='Desription')),
            ],
        ),
        migrations.RemoveField(
            model_name='image',
            name='src',
        ),
        migrations.AddField(
            model_name='image',
            name='image',
            field=models.ImageField(null=True, upload_to='media/'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='user_image',
            field=models.ImageField(null=True, upload_to='media/'),
        ),
        migrations.AlterField(
            model_name='product',
            name='rootImage',
            field=models.ImageField(null=True, upload_to='media/'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='policy',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='policy', to='shopapp.userpolicy'),
        ),
    ]
