# Generated by Django 4.1.2 on 2023-02-14 07:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shopapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='Quanlity_remaining',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='product',
            name='rootImage',
            field=models.CharField(default=None, max_length=254, verbose_name='RootImage'),
        ),
        migrations.DeleteModel(
            name='DetailProduct',
        ),
    ]
