# Generated by Django 4.1.2 on 2023-03-20 11:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shopapp', '0002_alter_userprofile_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='billorder',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='Created At'),
        ),
        migrations.AddField(
            model_name='billorder',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, null=True, verbose_name='Updated At'),
        ),
        migrations.AddField(
            model_name='comment',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='Created At'),
        ),
        migrations.AddField(
            model_name='comment',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, null=True, verbose_name='Updated At'),
        ),
        migrations.AddField(
            model_name='historicalbillorder',
            name='created_at',
            field=models.DateTimeField(blank=True, editable=False, null=True, verbose_name='Created At'),
        ),
        migrations.AddField(
            model_name='historicalbillorder',
            name='updated_at',
            field=models.DateTimeField(blank=True, editable=False, null=True, verbose_name='Updated At'),
        ),
        migrations.AddField(
            model_name='historicalproduct',
            name='created_at',
            field=models.DateTimeField(blank=True, editable=False, null=True, verbose_name='Created At'),
        ),
        migrations.AddField(
            model_name='historicalproduct',
            name='updated_at',
            field=models.DateTimeField(blank=True, editable=False, null=True, verbose_name='Updated At'),
        ),
        migrations.AddField(
            model_name='historicalproductcategory',
            name='created_at',
            field=models.DateTimeField(blank=True, editable=False, null=True, verbose_name='Created At'),
        ),
        migrations.AddField(
            model_name='historicalproductcategory',
            name='updated_at',
            field=models.DateTimeField(blank=True, editable=False, null=True, verbose_name='Updated At'),
        ),
        migrations.AddField(
            model_name='historicalwallet',
            name='created_at',
            field=models.DateTimeField(blank=True, editable=False, null=True, verbose_name='Created At'),
        ),
        migrations.AddField(
            model_name='historicalwallet',
            name='updated_at',
            field=models.DateTimeField(blank=True, editable=False, null=True, verbose_name='Updated At'),
        ),
        migrations.AddField(
            model_name='image',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='Created At'),
        ),
        migrations.AddField(
            model_name='image',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, null=True, verbose_name='Updated At'),
        ),
        migrations.AddField(
            model_name='orderring',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='Created At'),
        ),
        migrations.AddField(
            model_name='orderring',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, null=True, verbose_name='Updated At'),
        ),
        migrations.AddField(
            model_name='product',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='Created At'),
        ),
        migrations.AddField(
            model_name='product',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, null=True, verbose_name='Updated At'),
        ),
        migrations.AddField(
            model_name='productcategory',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='Created At'),
        ),
        migrations.AddField(
            model_name='productcategory',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, null=True, verbose_name='Updated At'),
        ),
        migrations.AddField(
            model_name='userpolicy',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='Created At'),
        ),
        migrations.AddField(
            model_name='userpolicy',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, null=True, verbose_name='Updated At'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='Created At'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, null=True, verbose_name='Updated At'),
        ),
        migrations.AddField(
            model_name='wallet',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='Created At'),
        ),
        migrations.AddField(
            model_name='wallet',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, null=True, verbose_name='Updated At'),
        ),
    ]
