# Generated by Django 4.1.2 on 2023-04-03 02:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shopapp', '0002_remove_historicalproductcategory_code_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='policy',
            field=models.ForeignKey(blank=True, default=1, on_delete=django.db.models.deletion.CASCADE, related_name='policy', to='shopapp.userpolicy'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='root_image',
            field=models.ImageField(blank=True, null=True, upload_to='image_user/'),
        ),
    ]
