# Generated by Django 4.1.2 on 2023-04-16 10:46

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shopapp', '0010_alter_image_product_alter_salecode_start_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cartitem',
            name='cart',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='items', to='shopapp.cart'),
        ),
        migrations.AlterField(
            model_name='cartitem',
            name='product',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='base_product', to='shopapp.baseproduct'),
        ),
        migrations.AlterField(
            model_name='salecode',
            name='start_time',
            field=models.DateField(blank=True, default=datetime.datetime(2023, 4, 16, 17, 46, 7, 114429), verbose_name='Start time'),
        ),
    ]
