# Generated by Django 4.1.2 on 2023-04-17 13:14

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shopapp', '0012_remove_cartitem_quanlity_cartitem_quantity_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='salecode',
            name='start_time',
            field=models.DateField(blank=True, default=datetime.datetime(2023, 4, 17, 20, 13, 55, 21183), verbose_name='Start time'),
        ),
    ]
