# Generated by Django 4.1.2 on 2023-04-04 14:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0004_cpu_ram_district_created_at_district_updated_at_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='inventoryinitem',
            name='cpu',
        ),
        migrations.RemoveField(
            model_name='inventoryinitem',
            name='ram',
        ),
        migrations.CreateModel(
            name='InventoryItemSerial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, null=True, verbose_name='Updated At')),
                ('cpu', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='product_cpu', to='inventory.cpu')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='item_serial', to='inventory.inventoryitem')),
                ('ram', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='product_ram', to='inventory.ram')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
