# Generated by Django 4.1.2 on 2023-04-05 09:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0005_remove_inventoryinitem_cpu_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='inventoryitemserial',
            name='cpu',
        ),
        migrations.RemoveField(
            model_name='inventoryitemserial',
            name='ram',
        ),
        migrations.AddField(
            model_name='inventoryitem',
            name='cpu',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='product_cpu', to='inventory.cpu'),
        ),
        migrations.AddField(
            model_name='inventoryitem',
            name='ram',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='product_ram', to='inventory.ram'),
        ),
        migrations.AddField(
            model_name='inventoryitemserial',
            name='serial',
            field=models.CharField(default=4209230361, max_length=50, verbose_name='Serial'),
        ),
    ]
