# Generated by Django 4.1.2 on 2023-04-11 04:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0006_remove_inventoryitemserial_cpu_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='inventoryout',
            name='inventory',
        ),
        migrations.RemoveField(
            model_name='inventoryoutitem',
            name='inventory_in',
        ),
        migrations.AlterField(
            model_name='inventoryitemserial',
            name='serial',
            field=models.CharField(default=2424201028, max_length=50, verbose_name='Serial'),
        ),
        migrations.DeleteModel(
            name='HistoricalInventoryOut',
        ),
        migrations.DeleteModel(
            name='InventoryOut',
        ),
        migrations.DeleteModel(
            name='InventoryOutItem',
        ),
    ]
