# Generated by Django 4.1.2 on 2023-04-13 04:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0007_remove_inventoryout_inventory_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inventoryitemserial',
            name='serial',
            field=models.CharField(default=6872390529, max_length=50, verbose_name='Serial'),
        ),
    ]
